# Generated by Django 2.2 on 2019-05-02 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20190502_1333'),
        ('posts', '0002_auto_20190502_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'message', 'group')},
        ),
    ]
